### ISSUE TITLE
Testando SOF

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/sof-brasil#1]
Segue arquivo
[teste-sof.docx](https://github.com/bireme/sof-brasil/files/767587/teste-sof.docx)

**Comment by renatomurasaki** [comment]
@wilsonmoura Por favor, revisar esta SOF aceita. Se possível, até sexta-feira.

Atentar-se para:

- [ ] Informar a bibliografia
- [ ] Nivel de evidencia

**Comment by renatomurasaki** [comment]
segue SOF Revisada
[teste-sof.docx](https://github.com/bireme/sof-brasil/files/767607/teste-sof.docx)

**Comment by renatomurasaki** [comment]
@viniciusandrade Favor realizar as alterações necessarias

**Comment by viniciusandrade** [comment]
@renatomurasaki Alterações realizadas.
